/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import barrionuevo.tp6.DirectorioTel;

/**
 *
 * @author Pablo
 */
public class BorrarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form BorrarCliente
     */
    public BorrarCliente() {
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        ldni = new javax.swing.JLabel();
        ladv = new javax.swing.JLabel();
        ltelefono = new javax.swing.JLabel();
        lapellido = new javax.swing.JLabel();
        lnombre = new javax.swing.JLabel();
        lciudad = new javax.swing.JLabel();
        lpregunta = new javax.swing.JLabel();
        lResultado = new javax.swing.JLabel();
        txtborrar = new javax.swing.JFormattedTextField();
        txttelefono = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtciudad = new javax.swing.JTextField();
        btnborrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setBackground(java.awt.Color.darkGray);
        setClosable(true);
        setForeground(java.awt.SystemColor.control);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Borrar Clientes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N

        lTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lTitulo.setForeground(java.awt.Color.white);
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("Borrar un cliente del Directorio Telefónico");

        ldni.setForeground(java.awt.Color.white);
        ldni.setText("D. N. I. Nº: ");

        ladv.setForeground(java.awt.Color.white);
        ladv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ladv.setText("Presione <ENTER> para buscar");

        ltelefono.setForeground(java.awt.Color.white);
        ltelefono.setText("Teléfono: ");

        lapellido.setForeground(java.awt.Color.white);
        lapellido.setText("Apellido/s: ");

        lnombre.setForeground(java.awt.Color.white);
        lnombre.setText("Nombre/s: ");

        lciudad.setForeground(java.awt.Color.white);
        lciudad.setText("Ciudad: ");

        lpregunta.setForeground(java.awt.Color.white);
        lpregunta.setText("Borrar Cliente?");

        lResultado.setForeground(java.awt.Color.white);
        lResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lResultado.setText("Resultado...");

        txtborrar.setBackground(java.awt.Color.darkGray);
        txtborrar.setForeground(java.awt.Color.white);
        txtborrar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        txtborrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtborrarKeyPressed(evt);
            }
        });

        txttelefono.setEditable(false);
        txttelefono.setBackground(java.awt.Color.darkGray);
        txttelefono.setForeground(java.awt.Color.white);

        txtapellido.setEditable(false);
        txtapellido.setBackground(java.awt.Color.darkGray);
        txtapellido.setForeground(java.awt.Color.white);

        txtnombre.setEditable(false);
        txtnombre.setBackground(java.awt.Color.darkGray);
        txtnombre.setForeground(java.awt.Color.white);

        txtciudad.setEditable(false);
        txtciudad.setBackground(java.awt.Color.darkGray);
        txtciudad.setForeground(java.awt.Color.white);

        btnborrar.setBackground(java.awt.Color.darkGray);
        btnborrar.setForeground(java.awt.Color.white);
        btnborrar.setText("Borrar Cliente");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(java.awt.Color.darkGray);
        btnSalir.setForeground(java.awt.Color.white);
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnombre)
                    .addComponent(lapellido)
                    .addComponent(ltelefono)
                    .addComponent(lciudad)
                    .addComponent(ldni))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtciudad)
                    .addComponent(txtnombre)
                    .addComponent(txtapellido)
                    .addComponent(txttelefono))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(txtborrar, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ladv)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lpregunta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnborrar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldni)
                    .addComponent(ladv)
                    .addComponent(txtborrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ltelefono)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lapellido)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lciudad)
                    .addComponent(txtciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lpregunta)
                    .addComponent(btnborrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        borrar();
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtborrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtborrarKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
            buscar();
    }//GEN-LAST:event_txtborrarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnborrar;
    private javax.swing.JLabel lResultado;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel ladv;
    private javax.swing.JLabel lapellido;
    private javax.swing.JLabel lciudad;
    private javax.swing.JLabel ldni;
    private javax.swing.JLabel lnombre;
    private javax.swing.JLabel lpregunta;
    private javax.swing.JLabel ltelefono;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JFormattedTextField txtborrar;
    private javax.swing.JTextField txtciudad;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
    
    //Mis atributos y métodos
    boolean puedeBorrar = false;
    private void iniciar() {
        initComponents();
        directorioEsVacio();
    }
    private void borrar() {
        Long aBorrar;
        if(puedeBorrar && !txtborrar.getText().isEmpty()){
            aBorrar = Long.parseLong(txtborrar.getText());
            if(aBorrar != 0L){
                DirectorioTel.dir.borrarCliente(aBorrar);
                lResultado.setText("Cliente con DNI: "+ txtborrar.getText() +", ha sido borrado...");
                //Actualizar la vista de Clientes
                Clientes.actualizartxt();
                Clientes.Tabla.borrar(txtborrar.getText());
                limpiar();
                directorioEsVacio();
            }
        }
    }

    private void buscar() {
        if(!txtborrar.getText().isEmpty()){
            recursos.Cliente cliente = DirectorioTel.dir.buscarPorDNI(Long.parseLong(txtborrar.getText()));
            if(cliente != null){
                txtapellido.setText(cliente.getApellido());
                txtnombre.setText(cliente.getNombre());
                txtciudad.setText(cliente.getCiudad());
                txttelefono.setText(String.valueOf(cliente.getTelefono()));
                lResultado.setText("Cliente a borrar ... DNI: "+ txtborrar.getText() +".");
                puedeBorrar = true;
            }else{
                limpiar();
                lResultado.setText("Escriba un DNI y presione <ENTER> para luego poder borrar");
                puedeBorrar = false;
            }
        }
    }

    private void limpiar() {
        txtborrar.setText("");
        txtapellido.setText("");
        txtnombre.setText("");
        txtciudad.setText("");
        txttelefono.setText("");
    }
    
    private void directorioEsVacio(){
        boolean vacio = DirectorioTel.dir.getKeys().length == 0;
        if(vacio){
            txtborrar.setEnabled(false);
            btnborrar.setEnabled(false);
            lResultado.setText("El directorio está vacio...");
        }else{
            txtborrar.setEnabled(true);
            btnborrar.setEnabled(true);
            lResultado.setText("Escriba un DNI y presione <ENTER> para luego poder borrar");
        }
    }
}
